library(psych)
describe(StudyTwoData$Dehuman_wht_1)
dfdehumanDV<- as.data.frame(cbind(StudyTwoData$Dehuman_wht_1,StudyTwoData$Dehuman_wht_2, 
                                  StudyTwoData$Dehuman_wht_3,StudyTwoData$Dehuman_wht_4,
                                  StudyTwoData$Dehuman_wht_5, StudyTwoData$Dehuman_wht_6, 
                                  StudyTwoData$Dehuman_wht_7, StudyTwoData$Dehuman_wht_8,
                                  StudyTwoData$Dehuman_wht_9, StudyTwoData$Dehuman_wht_10,
                                  StudyTwoData$Dehuman_wht_11, StudyTwoData$Dehuman_wht_12,
                                  StudyTwoData$Dehuman_wht_13, StudyTwoData$Dehuman_wht_14,
                                  StudyTwoData$Dehuman_wht_15, StudyTwoData$Dehuman_wht_16,
                                  StudyTwoData$Dehuman_wht_17, StudyTwoData$Dehuman_wht_18,
                                  StudyTwoData$Dehuman_wht_19, StudyTwoData$Dehuman_wht_20,
                                  StudyTwoData$Dehuman_Native_1, StudyTwoData$Dehuman_Native_2, 
                                  StudyTwoData$Dehuman_Native_3, StudyTwoData$Dehuman_Native_4,
                                  StudyTwoData$Dehuman_Native_5,StudyTwoData$Dehuman_Native_6,
                                  StudyTwoData$Dehuman_Native_7,StudyTwoData$Dehuman_Native_8,
                                  StudyTwoData$Dehuman_Native_9, StudyTwoData$Dehuman_Native_10,
                                  StudyTwoData$Dehuman_Native_11, StudyTwoData$Dehuman_Native_12,
                                  StudyTwoData$Dehuman_Native_13, StudyTwoData$Dehuman_Native_14,
                                  StudyTwoData$Dehuman_Native_15, StudyTwoData$Dehuman_Native_16,
                                  StudyTwoData$Dehuman_Native_17, StudyTwoData$Dehuman_Native_18,
                                  StudyTwoData$Dehuman_Native_19, StudyTwoData$Dehuman_Native_20, 
                                  StudyTwoData$DV1_1, StudyTwoData$DV1_2, StudyTwoData$DV1_3,
                                  StudyTwoData$DV1_4, StudyTwoData$DV1_5, StudyTwoData$DV1_6, StudyTwoData$DV1_7,
                                  StudyTwoData$DV1_8, StudyTwoData$DV1_9, StudyTwoData$DV1_10, StudyTwoData$DV1_11,
                                  StudyTwoData$DV2_Q38_1, StudyTwoData$DV2_Q38_2, StudyTwoData$DV2_Q38_3,
                                  StudyTwoData$DV2_Q38_4, StudyTwoData$DV2_Q38_5, StudyTwoData$DV2_Q38_6, 
                                  StudyTwoData$DV2_Q38_7, StudyTwoData$DV2_Q38_8, StudyTwoData$DV2_Q38_9,
                                  StudyTwoData$DV2_Q38_10, StudyTwoData$DV2_Q38_11, StudyTwoData$DV2_Q38_12, StudyTwoData$DV2_DV2_9,
                                  StudyTwoData$DV2_DV2_13, StudyTwoData$DV2_DV2_14, StudyTwoData$DV3_Q39_1, StudyTwoData$DV3_Q39_2,
                                  StudyTwoData$DV3_Q39_4, StudyTwoData$DV3_Q39_5, StudyTwoData$DV3_Q39_6, StudyTwoData$DV3_Q39_7,
                                  StudyTwoData$DV3_Q39_8, StudyTwoData$DV3_Q39_9))

View(dfdehumanDV)

colnames(dfdehumanDV) <- c(V1 = "Dehuman_wht_1",
                           V2 ="Dehuman_wht_2", 
                           V3 = "Dehuman_wht_3",V4 = "Dehuman_wht_4",
                           V5 = "Dehuman_wht_5",V6 = "Dehuman_wht_6", 
                           V7 = "Dehuman_wht_7",V8 = "Dehuman_wht_8",
                           V9 = "Dehuman_wht_9", V10 = "Dehuman_wht_10",
                           V11 = "Dehuman_wht_11",V12 = "Dehuman_wht_12",
                           V13 = "Dehuman_wht_13",V14 = "Dehuman_wht_14",
                           V15 = "Dehuman_wht_15", V16 = "Dehuman_wht_16",
                           V17 = "Dehuman_wht_17", V18="Dehuman_wht_18",
                           V19 =  "Dehuman_wht_19", V20 = "Dehuman_wht_20",
                           V21 =  "Dehuman_Native_1",V22 = "Dehuman_Native_2", 
                           V23 = "Dehuman_Native_3", V24 = "Dehuman_Native_4",
                           V25 = "Dehuman_Native_5", V26 = "Dehuman_Native_6",
                           V27 = "Dehuman_Native_7",V28 = "Dehuman_Native_8",
                           V29 =  "Dehuman_Native_9", V30 = "Dehuman_Native_10",
                           V31 = "Dehuman_Native_11", V32 =  "Dehuman_Native_12",
                           V33 = "Dehuman_Native_13", V34 ="Dehuman_Native_14",
                           V35 = "Dehuman_Native_15", V36 = "Dehuman_Native_16",
                           V37 = "Dehuman_Native_17", V38 = "Dehuman_Native_18",
                           V39 = "Dehuman_Native_19", V40 =  "Dehuman_Native_20", 
                           V41 = "DV1_1", V42 = "DV1_2", V43 = "DV1_3",
                           V44 = "DV1_4", V45 = "DV1_5", V46 = "DV1_6", V47 = "DV1_7",
                           V48 = "DV1_8", V49 = "DV1_9", V50 = "DV1_10", V51 = "DV1_11",
                           V52 = "DV2_Q38_1", V53 = "DV2_Q38_2", V54 = "DV2_Q38_3",
                           V55 = "DV2_Q38_4", V56 = "DV2_Q38_5", V57 = "DV2_Q38_6", 
                           V58 = "DV2_Q38_7", V59 = "DV2_Q38_8", V60 = "DV2_Q38_9",
                           V61 = "DV2_Q38_10", V62 = "DV2_Q38_11", V63 = "DV2_Q38_12", V64 ="DV2_DV2_9",
                           V65 = "DV2_DV2_13", V66 = "DV2_DV2_14", V67 = "DV3_Q39_1", V68 = "DV3_Q39_2",
                           V69 ="DV3_Q39_4", V70 = "DV3_Q39_5", V71 = "DV3_Q39_6", V72 = "DV3_Q39_7",
                           V73 ="DV3_Q39_8", V74 ="DV3_Q39_9")


describe(dfdehumanDV)